services:
  dev:
    image: node:18.15.0-alpine
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - 8080:8080
      - 35729:35729
volumes:
  nodemodules:
    external: true

