# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  docker:
    cmds:
      - node docker-engine.mjs
    
  setup:
    cmds:
      - docker volume create nodemodules
  
  install:
    cmds:
      - docker compose -f compose.install.yaml up
      
  server:
    cmds:
      - docker compose up
      
  dev:
    cmds:
      - task docker setup install server
      
  build:
    cmds:
      - docker build -t docker-node-dev-auto-refresh-esm-image .
      
  remove:
    cmds:
      - docker rm docker-node-dev-auto-refresh-esm-image -f
      
  run:
    cmds:
      - docker container run -d --name docker-node-dev-auto-refresh-esm-image -p 8080:8080 docker-node-dev-auto-refresh-esm-image
      
  start:
    cmds:
      - task build remove run
      
  stop:
    cmds:
      - docker stop docker-node-dev-auto-refresh-esm-image
