# https://taskfile.dev

version: '3'

vars:
  IMAGE_NAME: docker-node-dev-auto-refresh-esm-image

tasks:
  default:
    cmds:
      - echo "Hello, World!"
    silent: true

  docker:
    cmds:
      - node docker-engine.mjs
    
  setup:
    cmds:
      - docker volume create nodemodules
  
  install:
    cmds:
      - docker compose -f compose.install.yaml up
      
  server:
    cmds:
      - docker compose up
      
  dev:
    cmds:
      - task docker setup install server
      
  build:
    cmds:
      - docker build -t {{.IMAGE_NAME}} .
      
  remove:
    cmds:
      - docker rm {{.IMAGE_NAME}} -f
      
  run:
    cmds:
      - docker container run -d --name {{.IMAGE_NAME}} -p 8080:8080 {{.IMAGE_NAME}}
      
  start:
    cmds:
      - task build remove run
      
  stop:
    cmds:
      - docker stop {{.IMAGE_NAME}}
